# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
