# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160410_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
